### PR TITLE
Add mode w540@2x flag

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Adds compatibility with [new ponscripter builds](https://github.com/07th-mod/ponscripter-fork/commit/d784b085e3025f11ba03a86fee885fe0bfeff5d8)
Ponscripter skips characters to the end of the line when it sees a directive it doesn't understand, so by putting the `modew540@2x` at the end, older builds will stay on default settings (the equivalent of not having it at all)

### CODE REVIEW

**Comment by drojf** [comment]
I'm not sure if you need to make more changes, but if you put all the changes you need in this PR, I can copy the changes to the variant scripts for you (to the voice-only branch etc.), and for the answer arcs.

**Comment by tellowkrinkle** [comment]
voice-only doesn't use 1080p right?

`modew540@2x` puts ponscripter in 960x540@2x AKA 1080p-with-scaled-images mode

**Comment by tellowkrinkle** [comment]
I set the default to 640x480@2x mode, as that's what the original umineko uses, which would allow you to use that ponscripter build without modifications with unmodded, 1080p modded, and ciconia (uses `modew720`)

**Comment by drojf** [comment]
Ah ok, voice-only doesn'tt need changes then. 

However the Answer Arcs ADV-mode script would need the `w540@2x` flag too, as it expects 1080p resolution.

**Comment by tellowkrinkle** [comment]
Yep, just made that one https://github.com/07th-mod/umineko-answer/pull/82

**Comment by drojf** [comment]
uh...it's confusing but there are three script variants for the answer arcs - "voice-only", "full", and "ADV". 

"full" is 1080p without ADV mode (NVL mode)
"ADV" is 1080p with ADV mode

the ADV script is on the `adv_mode` branch: https://github.com/07th-mod/umineko-answer/blob/adv_mode/0.utf

**Comment by tellowkrinkle** [comment]
Oh
I'll cherry-pick the commit after I merge onto the main branch I guess

**Comment by drojf** [comment]
yes that's fine

**Pull request merged**
