### PR TITLE
Ep1-2 CGs, high resolution scroll, corrected lighting issues, translated TsuruPettan NND scroll.

### PR DESCRIPTION
**Pull request by ReitoKanzaki**
Episode 1 and Episode 2 major overhaul. Added PS3 CGs. Edited sprites. Implemented high resolution credit scroll.

### CODE REVIEW

**Comment by ItaloKnox** [comment]
Kinda scratching my head here to solve the conflict. Command line is not helping and the Github desktop is a mess.

**Comment by ReitoKanzaki** [comment]
Yeah, I noticed that last night. I thought I was using a recent version of the script.

**Comment by ItaloKnox** [comment]
You can use WinMerge to fix it with a most recent version and then commit the change. I'm not really used to merge stuff with the command line so it doesn't seem to work very well.

**Comment by ReitoKanzaki** [comment]
I used WinMerge and combed through all the diffs. I even found a spot where I forgot to put in clr_oldnew_bg.

**Comment by DoctorDiablo** [comment]
Man, resolving conflicts in Git is a pain.  It's probably easiest to just fix the file outside of Git.

It looks like your branch was based on pull request #28, so if you diff [this](https://github.com/07th-mod/umineko-question/blob/7d5bbcaffc9349630e21d320170d8bcfb6bc87f3/InDevelopment/ManualUpdates/0.utf) version of 0.utf with the [latest](https://github.com/07th-mod/umineko-question/blob/master/InDevelopment/ManualUpdates/0.utf) in the master branch and make sure all of those changes are applied in your version, it should resolve the conflict.

Or if you did that already and it's still not resolving the conflict... maybe you should cancel this pull request, pull the latest master version into your branch with a pull request of your own, drop your changes on top of that, and then submit a new pull request so GitHub thinks it was based on the most recent version.

**Pull request closed without merging**
